"""add stale to collectable

Revision ID: 411e982acb3a
Revises: 784e2845926c
Create Date: 2021-09-28 06:26:11.890427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411e982acb3a'
down_revision = '784e2845926c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collectables', sa.Column('stale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collectables', 'stale')
    # ### end Alembic commands ###
