"""initial

Revision ID: 784e2845926c
Revises: 
Create Date: 2021-09-27 22:00:13.479954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "784e2845926c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collectables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_name", sa.String(), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "collection_name", "collection_id", name="_collection_name_id_uc"
        ),
    )
    op.create_index(
        op.f("ix_collectables_collection_id"),
        "collectables",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collectables_collection_name"),
        "collectables",
        ["collection_name"],
        unique=False,
    )
    op.create_index(op.f("ix_collectables_id"), "collectables", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_collectables_id"), table_name="collectables")
    op.drop_index(op.f("ix_collectables_collection_name"), table_name="collectables")
    op.drop_index(op.f("ix_collectables_collection_id"), table_name="collectables")
    op.drop_table("collectables")
    # ### end Alembic commands ###
