"""create collection table

Revision ID: 9172f2c48f12
Revises: 795e62a4a7f8
Create Date: 2021-10-02 06:02:30.697364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9172f2c48f12"
down_revision = "795e62a4a7f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("progress_count", sa.Integer(), nullable=True),
        sa.Column("collectables_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_collections_id"), "collections", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_collections_id"), table_name="collections")
    op.drop_table("collections")
    # ### end Alembic commands ###
