"""set collection progress_count default to 0

Revision ID: a898e55067e2
Revises: 9172f2c48f12
Create Date: 2021-10-02 06:11:23.570363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a898e55067e2"
down_revision = "9172f2c48f12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
