"""initial

Revision ID: ea6776443d9f
Revises: 
Create Date: 2021-10-03 06:25:48.142501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ea6776443d9f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collectables",
        sa.Column("id", sa.String(), autoincrement=False, nullable=False),
        sa.Column("collection_name", sa.String(), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("stale", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "collection_name", "collection_id", name="_collection_name_id_uc"
        ),
    )
    op.create_index(
        op.f("ix_collectables_collection_id"),
        "collectables",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collectables_collection_name"),
        "collectables",
        ["collection_name"],
        unique=False,
    )
    op.create_index(op.f("ix_collectables_id"), "collectables", ["id"], unique=False)
    op.create_index(
        op.f("ix_collectables_rank"), "collectables", ["rank"], unique=False
    )
    op.create_index(
        op.f("ix_collectables_score"), "collectables", ["score"], unique=False
    )
    op.create_index(
        op.f("ix_collectables_stale"), "collectables", ["stale"], unique=False
    )
    op.create_table(
        "collections",
        sa.Column("id", sa.String(), autoincrement=False, nullable=False),
        sa.Column("progress_count", sa.Integer(), nullable=True),
        sa.Column("collectables_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_collections_id"), "collections", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_collections_id"), table_name="collections")
    op.drop_table("collections")
    op.drop_index(op.f("ix_collectables_stale"), table_name="collectables")
    op.drop_index(op.f("ix_collectables_score"), table_name="collectables")
    op.drop_index(op.f("ix_collectables_rank"), table_name="collectables")
    op.drop_index(op.f("ix_collectables_id"), table_name="collectables")
    op.drop_index(op.f("ix_collectables_collection_name"), table_name="collectables")
    op.drop_index(op.f("ix_collectables_collection_id"), table_name="collectables")
    op.drop_table("collectables")
    # ### end Alembic commands ###
