name: Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'docker-entrypoint.sh'
      - '.github/workflows/continuous-deployment.yml'
      - 'README.md'
      - 'prepare.py'
      - 'rarity_tools_scraper_api/**'
      - 'rarity_tools_scraper_lib/**'
      - 'rarity_tools_scraper_data/**'

jobs:
  PushToRegistry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Add Docker tags
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
